constexpr auto bStartAILogicOnPossess = 0x2e8; // char : 1
constexpr auto bStopAILogicOnUnposses = 0x2e8; // char : 1
constexpr auto bLOSflag = 0x2e8; // char : 1
constexpr auto bSkipExtraLOSChecks = 0x2e8; // char : 1
constexpr auto bAllowStrafe = 0x2e8; // char : 1
constexpr auto bWantsPlayerState = 0x2e8; // char : 1
constexpr auto bSetControlRotationFromPawnOrientation = 0x2e8; // char : 1
constexpr auto PathFollowingComponent = 0x2f0; // UPathFollowingComponent*
constexpr auto BrainComponent = 0x2f8; // UBrainComponent*
constexpr auto PerceptionComponent = 0x300; // UAIPerceptionComponent*
constexpr auto ActionsComp = 0x308; // UPawnActionsComponent*
constexpr auto Blackboard = 0x310; // UBlackboardComponent*
constexpr auto CachedGameplayTasksComponent = 0x318; // UGameplayTasksComponent*
constexpr auto DefaultNavigationFilterClass = 0x320; // UNavigationQueryFilter*
constexpr auto ReceiveMoveCompleted = 0x328; // FMulticastInlineDelegate
constexpr auto PreviewImageData = 0x2a8; // TArray<char>
constexpr auto ARWorldData = 0x2b8; // TArray<char>
constexpr auto PreviewImageBytesTotal = 0x2c8; // int32_t
constexpr auto ARWorldBytesTotal = 0x2cc; // int32_t
constexpr auto PreviewImageBytesDelivered = 0x2d0; // int32_t
constexpr auto ARWorldBytesDelivered = 0x2d4; // int32_t
constexpr auto PrimaryActorTick = 0x30; // FActorTickFunction
constexpr auto bHidden = 0x60; // char : 1
constexpr auto bForceNetAddressable = 0x60; // char : 1
constexpr auto bTearOff = 0x60; // char : 1
constexpr auto bNetTemporary = 0x60; // char : 1
constexpr auto bReplicateMovement = 0x60; // char : 1
constexpr auto bAlwaysRelevant = 0x60; // char : 1
constexpr auto bOnlyRelevantToOwner = 0x60; // char : 1
constexpr auto bNetStartup = 0x60; // char : 1
constexpr auto bExchangedRoles = 0x61; // char : 1
constexpr auto bNetUseOwnerRelevancy = 0x61; // char : 1
constexpr auto bRelevantForNetworkReplays = 0x61; // char : 1
constexpr auto bRelevantForLevelBounds = 0x61; // char : 1
constexpr auto bReplayRewindable = 0x61; // char : 1
constexpr auto bAllowTickBeforeBeginPlay = 0x61; // char : 1
constexpr auto bAutoDestroyWhenFinished = 0x61; // char : 1
constexpr auto bNetLoadOnClient = 0x61; // char : 1
constexpr auto bIgnoresOriginShifting = 0x62; // char : 1
constexpr auto bIsEditorOnlyActor = 0x62; // char : 1
constexpr auto bEnableAutoLODGeneration = 0x62; // char : 1
constexpr auto bCollideWhenPlacing = 0x62; // char : 1
constexpr auto bGenerateOverlapEventsDuringLevelStreaming = 0x62; // char : 1
constexpr auto bFindCameraComponentWhenViewTarget = 0x62; // char : 1
constexpr auto bBlockInput = 0x62; // char : 1
constexpr auto bCanBeDamaged = 0x62; // char : 1
constexpr auto bActorSeamlessTraveled = 0x63; // char : 1
constexpr auto bReplicates = 0x63; // char : 1
constexpr auto bCanBeInCluster = 0x63; // char : 1
constexpr auto bAllowReceiveTickEventOnDedicatedServer = 0x63; // char : 1
constexpr auto bActorEnableCollision = 0x64; // char : 1
constexpr auto bActorIsBeingDestroyed = 0x64; // char : 1
constexpr auto UpdateOverlapsMethodDuringLevelStreaming = 0x65; // EActorUpdateOverlapsMethod
constexpr auto DefaultUpdateOverlapsMethodDuringLevelStreaming = 0x66; // EActorUpdateOverlapsMethod
constexpr auto RemoteRole = 0x67; // ENetRole
constexpr auto ReplicatedMovement = 0x68; // FRepMovement
constexpr auto InitialLifeSpan = 0x9c; // float
constexpr auto CustomTimeDilation = 0xa0; // float
constexpr auto AttachmentReplication = 0xa8; // FRepAttachment
constexpr auto Owner = 0xe8; // AActor*
constexpr auto NetDriverName = 0xf0; // FName
constexpr auto Role = 0xfc; // ENetRole
constexpr auto NetDormancy = 0xfd; // ENetDormancy
constexpr auto SpawnCollisionHandlingMethod = 0xfe; // ESpawnActorCollisionHandlingMethod
constexpr auto AutoReceiveInput = 0xff; // EAutoReceiveInput
constexpr auto InputPriority = 0x100; // int32_t
constexpr auto InputComponent = 0x108; // UInputComponent*
constexpr auto NetCullDistanceSquared = 0x110; // float
constexpr auto NetTag = 0x114; // int32_t
constexpr auto NetUpdateFrequency = 0x118; // float
constexpr auto MinNetUpdateFrequency = 0x11c; // float
constexpr auto NetPriority = 0x120; // float
constexpr auto Instigator = 0x128; // APawn*
constexpr auto Children = 0x130; // TArray<AActor*>
constexpr auto RootComponent = 0x140; // USceneComponent*
constexpr auto ControllingMatineeActors = 0x148; // TArray<AMatineeActor*>
constexpr auto Layers = 0x160; // TArray<FName>
constexpr auto ParentComponent = 0x170; // TWeakObjectPtr<UChildActorComponent>
constexpr auto Tags = 0x180; // TArray<FName>
constexpr auto OnTakeAnyDamage = 0x190; // FMulticastSparseDelegate
constexpr auto OnTakePointDamage = 0x191; // FMulticastSparseDelegate
constexpr auto OnTakeRadialDamage = 0x192; // FMulticastSparseDelegate
constexpr auto OnActorBeginOverlap = 0x193; // FMulticastSparseDelegate
constexpr auto OnActorEndOverlap = 0x194; // FMulticastSparseDelegate
constexpr auto OnBeginCursorOver = 0x195; // FMulticastSparseDelegate
constexpr auto OnEndCursorOver = 0x196; // FMulticastSparseDelegate
constexpr auto OnReleased = 0x198; // FMulticastSparseDelegate
constexpr auto OnInputTouchBegin = 0x199; // FMulticastSparseDelegate
constexpr auto OnInputTouchEnd = 0x19a; // FMulticastSparseDelegate
constexpr auto OnInputTouchEnter = 0x19b; // FMulticastSparseDelegate
constexpr auto OnInputTouchLeave = 0x19c; // FMulticastSparseDelegate
constexpr auto OnActorHit = 0x19d; // FMulticastSparseDelegate
constexpr auto OnDestroyed = 0x19e; // FMulticastSparseDelegate
constexpr auto OnEndPlay = 0x19f; // FMulticastSparseDelegate
constexpr auto InstanceComponents = 0x200; // TArray<UActorComponent*>
constexpr auto BlueprintCreatedComponents = 0x210; // TArray<UActorComponent*>
constexpr auto UberGraphFrame = 0x1980; // FPointerToUberGraphFrame
constexpr auto IgnorePlayersCollisions = 0x1988; // UIgnorePlayersCollisionsComponent*
constexpr auto Ak_Audio_Killer_NoOcclusion = 0x1990; // UAkComponent*
constexpr auto BP_AfterImageComponent = 0x1998; // UBP_AfterImageComponent_C*
constexpr auto BP_Audio_KLR_28 = 0x19a0; // UBP_Audio_KLR_27_C*
constexpr auto SlashAttack_BP_C = 0x19a8; // USlashAttack_BP_C*
constexpr auto PounceAttack_BP_C = 0x19b0; // UPounceAttack_BP_C*
constexpr auto TML_VignetteIntensityOnInteraction_InteractionVignetteVanish_19417BB8491889DE9FDC42BE330FFFDD = 0x19b8; // float
constexpr auto TML_VignetteIntensityOnInteraction__Direction_19417BB8491889DE9FDC42BE330FFFDD = 0x19bc; // ETimelineDirection
constexpr auto TML_VignetteIntensityOnInteraction = 0x19c0; // UTimelineComponent*
constexpr auto TML_TeleportHideMesh_NewTrack_0_00E7BDF14A0844E3B8BCBDB228CC22D8 = 0x19c8; // float
constexpr auto TML_TeleportHideMesh__Direction_00E7BDF14A0844E3B8BCBDB228CC22D8 = 0x19cc; // ETimelineDirection
constexpr auto TML_TeleportHideMesh = 0x19d0; // UTimelineComponent*
constexpr auto TML_TeleportFeet_VaultOpacityDissolveLvl_2155BA49426F5ED7364FE88DDA5883B4 = 0x19d8; // float
constexpr auto TML_TeleportFeet__Direction_2155BA49426F5ED7364FE88DDA5883B4 = 0x19dc; // ETimelineDirection
constexpr auto TML_TeleportFeet = 0x19e0; // UTimelineComponent*
constexpr auto TML_Unmanifest_PowerScaling_5390BF654162A90BA43CDCB423451EBF = 0x19e8; // float
constexpr auto TML_Unmanifest_Vignette_Intensity_5390BF654162A90BA43CDCB423451EBF = 0x19ec; // float
constexpr auto TML_Unmanifest__Direction_5390BF654162A90BA43CDCB423451EBF = 0x19f0; // ETimelineDirection
constexpr auto TML_Unmanifest = 0x19f8; // UTimelineComponent*
constexpr auto TML_Manifest_PowerScaling_C8B2EF204D929F27887891B9BEA446ED = 0x1a00; // float
constexpr auto TML_Manifest_Vignette_Intensity_C8B2EF204D929F27887891B9BEA446ED = 0x1a04; // float
constexpr auto TML_Manifest__Direction_C8B2EF204D929F27887891B9BEA446ED = 0x1a08; // ETimelineDirection
constexpr auto TML_Manifest = 0x1a10; // UTimelineComponent*
constexpr auto TML_Opacity_Opacity_Hair_98033A1B44F8FE679812E7804399EB22 = 0x1a18; // float
constexpr auto TML_Opacity_Opacity_Body_98033A1B44F8FE679812E7804399EB22 = 0x1a1c; // float
constexpr auto TML_Opacity__Direction_98033A1B44F8FE679812E7804399EB22 = 0x1a20; // ETimelineDirection
constexpr auto TML_Opacity = 0x1a28; // UTimelineComponent*
constexpr auto FadeToBlackTimeline_FadeToBlack_Use_5BE29A02433314C96C4BBFA8BFBA26EA = 0x1a30; // float
constexpr auto FadeToBlackTimeline_Vignette_Intensity_5BE29A02433314C96C4BBFA8BFBA26EA = 0x1a34; // float
constexpr auto FadeToBlackTimeline_Outline_5BE29A02433314C96C4BBFA8BFBA26EA = 0x1a38; // float
constexpr auto FadeToBlackTimeline_FadeIntensity_5BE29A02433314C96C4BBFA8BFBA26EA = 0x1a3c; // float
constexpr auto FadeToBlackTimeline__Direction_5BE29A02433314C96C4BBFA8BFBA26EA = 0x1a40; // ETimelineDirection
constexpr auto FadeToBlackTimeline = 0x1a48; // UTimelineComponent*
constexpr auto PPVignetteBasicFadeToBlack = 0x1a50; // UMaterialInstanceDynamic*
constexpr auto prevFadeToBlackBasicSize = 0x1a58; // float
constexpr auto IsForwardFade = 0x1a5c; // bool
constexpr auto PP_Vignette_K27_Manifest = 0x1a60; // UMaterialInstanceDynamic*
constexpr auto Manifest_WeightedBlendable = 0x1a68; // FWeightedBlendable
constexpr auto Manifest_WeightedBlendables = 0x1a78; // TArray<FWeightedBlendable>
constexpr auto NS_FX_Manifest_Charge = 0x1a88; // TArray<UNiagaraComponent*>
constexpr auto IsTeleporting = 0x1a98; // bool
constexpr auto NS_FX_Manifest_Charge_02 = 0x1aa0; // UNiagaraComponent*
constexpr auto FadeToBlack_WeightedBlendable = 0x1aa8; // FWeightedBlendable
constexpr auto FadeToBlack_WeightedBlendables = 0x1ab8; // TArray<FWeightedBlendable>
constexpr auto AB_Slasher_28 = 0x1ac8; // UAB_Slasher_27_C*
constexpr auto Teleport_VeinsColor = 0x1ad0; // FVector
constexpr auto IsManifested = 0x1adc; // bool
constexpr auto WantsVisible = 0x1add; // bool
constexpr auto IsInTeleportInteraction = 0x1ade; // bool
constexpr auto IsVisible = 0x1adf; // bool
constexpr auto IsFlickeringStopped = 0x1ae0; // bool
constexpr auto UberGraphFrame = 0x1600; // FPointerToUberGraphFrame
constexpr auto PositionLagCompensation = 0x1608; // UPositionLagCompensationComponent*
constexpr auto CharacterOptimizer = 0x1610; // UCharacterOptimizer*
constexpr auto WiggleMotion = 0x1618; // UWiggleMotionComponent*
constexpr auto Ethereal = 0x1620; // UEtherealComponent*
constexpr auto KillerFlashlightSFX = 0x1628; // UKillerFlashlightSFXComponent*
constexpr auto InteractionAnalytics = 0x1630; // UInteractionAnalyticsComponent*
constexpr auto BlindFlashlightTargetFX = 0x1638; // UBlindFlashlightTargetFXComponent*
constexpr auto BodyFlashlightable = 0x1640; // UFlashlightableComponent*
constexpr auto EyesFlashlightable = 0x1648; // UFlashlightableComponent*
constexpr auto LeftFootGroundDetector = 0x1650; // UBP_KillerLeftFootGroundDetector_C*
constexpr auto RightFootGroundDetector = 0x1658; // UBP_KillerRightFootGroundDetector_C*
constexpr auto QuestEventsHandler = 0x1660; // UQuestEventsHandler*
constexpr auto RedStainComponent = 0x1668; // UBP_RedStainComponent_C*
constexpr auto GameEventListenerCollection = 0x1670; // UGameEventListenerCollectionComponent*
constexpr auto pawnDetector = 0x1678; // UCapsulePlayerOverlapComponent*
constexpr auto ScreenSpaceLocation_MiddleT = 0x1680; // UScreenSpaceLocationComponent*
constexpr auto P_Vignette_EndGame_Top = 0x1688; // UParticleSystemComponent*
constexpr auto EndGameEffectsComponent = 0x1690; // UEndGameEffectsComponent_C*
constexpr auto Camera1 = 0x1698; // UCameraComponent*
constexpr auto SlasherOutlineUpdateStrategy = 0x16a0; // USlasherOutlineUpdateStrategy*
constexpr auto CustomizedAudio = 0x16a8; // UCustomizedAudioComponent*
constexpr auto BlindedPostProcess_new = 0x16b0; // UPostProcessComponent*
constexpr auto AttackZone_004 = 0x16b8; // UStaticMeshComponent*
constexpr auto audioAmbientDetector = 0x16c0; // USphereComponent*
constexpr auto AttackZone_Wedge_Large = 0x16c8; // UStaticMeshComponent*
constexpr auto AttackZone_Wedge_Standard = 0x16d0; // UStaticMeshComponent*
constexpr auto VignetteBloodlust = 0x16d8; // UPostProcessComponent*
constexpr auto FirecrackerEffectHandler = 0x16e0; // UFirecrackerEffectHandlerComponent*
constexpr auto AttackZoneHigh_003 = 0x16e8; // UStaticMeshComponent*
constexpr auto AttackZoneHigh_002 = 0x16f0; // UStaticMeshComponent*
constexpr auto AttackZoneHigh_001 = 0x16f8; // UStaticMeshComponent*
constexpr auto ObstructionShape = 0x1700; // UBoxComponent*
constexpr auto AttackZone_003 = 0x1708; // UStaticMeshComponent*
constexpr auto AttackZone_002 = 0x1710; // UStaticMeshComponent*
constexpr auto AttackZone_001 = 0x1718; // UStaticMeshComponent*
constexpr auto attackZonePivot = 0x1720; // USceneComponent*
constexpr auto Ak_Audio_Killer = 0x1728; // UAkComponent*
constexpr auto ChainsawObstruction = 0x1730; // UBoxComponent*
constexpr auto InteractionDetector = 0x1738; // UCapsuleComponent*
constexpr auto CamperDropOffPoint = 0x1740; // USceneComponent*
constexpr auto DBDOutline = 0x1748; // UDBDOutlineComponent*
constexpr auto CustomizedSkeletalMesh = 0x1750; // UCustomizedSkeletalMesh*
constexpr auto BP_Mesh2SoundPlayer = 0x1758; // UBP_Mesh2SoundPlayer_C*
constexpr auto BlinkAttackLockZone = 0x1760; // UBoxComponent*
constexpr auto ScreenSpaceLocation_LeftT = 0x1768; // UScreenSpaceLocationComponent*
constexpr auto ScreenSpaceLocation_RightT = 0x1770; // UScreenSpaceLocationComponent*
constexpr auto P_Vignette_LeftB = 0x1778; // UParticleSystemComponent*
constexpr auto ScreenSpaceLocation_LeftB = 0x1780; // UScreenSpaceLocationComponent*
constexpr auto P_Vignette_RightB = 0x1788; // UParticleSystemComponent*
constexpr auto ScreenSpaceLocation_RightB = 0x1790; // UScreenSpaceLocationComponent*
constexpr auto LoudNoiseHUDIndicator = 0x1798; // ULoudNoiseHUDIndicator*
constexpr auto Fx_FSbloodfx = 0x17a0; // UParticleSystemComponent*
constexpr auto TML_LungeAttack_Vignette_C6A1D26A45B8D21BE38076A15A900F67 = 0x17a8; // float
constexpr auto TML_LungeAttack__Direction_C6A1D26A45B8D21BE38076A15A900F67 = 0x17ac; // ETimelineDirection
constexpr auto TML_LungeAttack = 0x17b0; // UTimelineComponent*
constexpr auto BloodSplatterOpacityAnim_NewTrack_0_C8565C8848DC851A61C85CA0D1C69D9F = 0x17b8; // float
constexpr auto BloodSplatterOpacityAnim__Direction_C8565C8848DC851A61C85CA0D1C69D9F = 0x17bc; // ETimelineDirection
constexpr auto BloodSplatterOpacityAnim = 0x17c0; // UTimelineComponent*
constexpr auto BloodSplatterFrameAnim_NewTrack_0_89AF70DC41EF75E7CD3BF6B72CCE267B = 0x17c8; // float
constexpr auto BloodSplatterFrameAnim__Direction_89AF70DC41EF75E7CD3BF6B72CCE267B = 0x17cc; // ETimelineDirection
constexpr auto BloodSplatterFrameAnim = 0x17d0; // UTimelineComponent*
constexpr auto TML_BlackSmoke_Atlanta_Fade_655F805E4CE3AB7F8F28689998ED7469 = 0x17d8; // float
constexpr auto TML_BlackSmoke_Atlanta__Direction_655F805E4CE3AB7F8F28689998ED7469 = 0x17dc; // ETimelineDirection
constexpr auto TML_BlackSmoke_Atlanta = 0x17e0; // UTimelineComponent*
constexpr auto TML_BlackSmoke_Distortion_B6144BAE404061D5F806EBBCA47DA5A3 = 0x17e8; // float
constexpr auto TML_BlackSmoke_Fade_B6144BAE404061D5F806EBBCA47DA5A3 = 0x17ec; // float
constexpr auto TML_BlackSmoke__Direction_B6144BAE404061D5F806EBBCA47DA5A3 = 0x17f0; // ETimelineDirection
constexpr auto TML_BlackSmoke = 0x17f8; // UTimelineComponent*
constexpr auto Bloodlust_Timeline_Blend_7510578B48E7070D9984B9923F94253F = 0x1800; // float
constexpr auto Bloodlust_Timeline__Direction_7510578B48E7070D9984B9923F94253F = 0x1804; // ETimelineDirection
constexpr auto BloodlustTimeline = 0x1808; // UTimelineComponent*
constexpr auto Timeline_1_Dissolve_99584B454ECDABDE86BE6E8CD0241B00 = 0x1810; // float
constexpr auto Timeline_1__Direction_99584B454ECDABDE86BE6E8CD0241B00 = 0x1814; // ETimelineDirection
constexpr auto Timeline_2 = 0x1818; // UTimelineComponent*
constexpr auto BaseTurnRate = 0x1820; // float
constexpr auto BaseLookUpRate = 0x1824; // float
constexpr auto CenterOfWorld = 0x1830; // FTransform
constexpr auto Attack = 0x1860; // bool
constexpr auto IsTurning = 0x1864; // float
constexpr auto CharacterHeadMesh = 0x1868; // UMaterialInstanceDynamic*
constexpr auto MeshMachette = 0x1870; // USkinnedMeshComponent*
constexpr auto TrapMaterial = 0x1878; // UMaterialInstanceDynamic*
constexpr auto TrapPlacementValid = 0x1880; // bool
constexpr auto TrapIndicatorOffset = 0x1884; // float
constexpr auto BaseMaxWalkSpeed = 0x1888; // float
constexpr auto baseTerrorRadius = 0x188c; // float
constexpr auto SurvivorBeingKilled = 0x1890; // ACamperPlayer*
constexpr auto DissolveMaterialGroupName = 0x1898; // FString
constexpr auto FirstPersonMaterialGroupName = 0x18a8; // FString
constexpr auto DissolveGroupName = 0x18b8; // FString
constexpr auto FirstPersonDissolve = 0x18c8; // FString
constexpr auto FirstPersonGroupName = 0x18d8; // FString
constexpr auto IsDissolving = 0x18e8; // bool
constexpr auto Weapon = 0x18ec; // FName
constexpr auto RootMeshIsHeadOnly = 0x18f8; // bool
constexpr auto TrapPlacementRaycastStart = 0x18fc; // FVector
constexpr auto TrapPlacementRaycastEnd = 0x1908; // FVector
constexpr auto MID_Damage = 0x1918; // UMaterialInstanceDynamic*
constexpr auto MID_LockOn = 0x1920; // UMaterialInstanceDynamic*
constexpr auto BlindnessCurve = 0x1928; // UCurveFloat*
constexpr auto BlindnessMaterialCurve = 0x1930; // UCurveFloat*
constexpr auto PP_Stun = 0x1938; // UMaterialInstanceDynamic*
constexpr auto PP_Smoke = 0x1940; // UMaterialInstanceDynamic*
constexpr auto PP_Chase = 0x1948; // UMaterialInstanceDynamic*
constexpr auto PPFlashlight = 0x1950; // UMaterialInstanceDynamic*
constexpr auto PP_SlasherBlood = 0x1958; // UMaterialInstanceDynamic*
constexpr auto DOFFocusPoint = 0x1960; // float
constexpr auto PP_LungeAttack = 0x1968; // UMaterialInstanceDynamic*
constexpr auto CameraSocketName = 0x1970; // FName
constexpr auto IsSnowmanActive = 0x197c; // bool
constexpr auto UberGraphFrame = 0x230; // FPointerToUberGraphFrame
constexpr auto MaterialHelper = 0x238; // UMaterialHelper*
constexpr auto StaticMesh = 0x240; // UStaticMeshComponent*
constexpr auto DefaultSceneRoot = 0x248; // USceneComponent*
constexpr auto TML_WellDissolveController_Dissolve_67D9A2534602A3F9B1003CA8800C736F = 0x250; // float
constexpr auto TML_WellDissolveController__Direction_67D9A2534602A3F9B1003CA8800C736F = 0x254; // ETimelineDirection
constexpr auto TML_WellDissolveController = 0x258; // UTimelineComponent*
constexpr auto UberGraphFrame = 0x230; // FPointerToUberGraphFrame
constexpr auto Actor_PostProcess_K27_Interrupt_01 = 0x238; // UPostProcessComponent*
constexpr auto DefaultSceneRoot = 0x240; // USceneComponent*
constexpr auto NewVar_1 = 0x250; // FPostProcessSettings
constexpr auto PP_InterruptIdle_01 = 0x7b0; // UMaterialInstanceDynamic*
constexpr auto RandomArray = 0x7b8; // TArray<float>
constexpr auto UberGraphFrame = 0x230; // FPointerToUberGraphFrame
constexpr auto Actor_PostProcess_K27_Interrupt_02 = 0x238; // UPostProcessComponent*
constexpr auto DefaultSceneRoot = 0x240; // USceneComponent*
constexpr auto TML_PP_IdleInterrupt_02_Int_Vignette_A015685E4996C78ADD577788FC36D84F = 0x248; // float
constexpr auto TML_PP_IdleInterrupt_02__Direction_A015685E4996C78ADD577788FC36D84F = 0x24c; // ETimelineDirection
constexpr auto TML_PP_IdleInterrupt_02 = 0x250; // UTimelineComponent*
constexpr auto PP_InterruptIdle_02 = 0x258; // UMaterialInstanceDynamic*
constexpr auto _interactable = 0x4b0; // USpherePlayerOverlapComponent*
constexpr auto _collectableInteractor = 0x4b8; // UInteractor*
constexpr auto _dropInteraction = 0x4c0; // UDropItemInteraction*
constexpr auto _collectInteraction = 0x4c8; // UCollectItemInteraction*
constexpr auto _infectablePrimitive = 0x4d0; // USphereComponent*
constexpr auto _outlineComponent = 0x4d8; // UDBDOutlineComponent*
constexpr auto _materialHelper = 0x4e0; // UMaterialHelper*
constexpr auto _survivorCollectableOutlineUpdateStrategy = 0x4e8; // USurvivorCollectableOutlineUpdateStrategy*
constexpr auto _gasType = 0x2b8; // EBombType
constexpr auto _poolableProjectile = 0x2c0; // UPoolableProjectileComponent*
constexpr auto _gasCloudDuration = 0x2c8; // FDBDTunableRowHandle
constexpr auto _gasCloudGravityScale = 0x2f0; // FDBDTunableRowHandle
constexpr auto _gasCloudBounciness = 0x318; // FDBDTunableRowHandle
constexpr auto _gasCloudFriction = 0x340; // FDBDTunableRowHandle
constexpr auto _dissipateGasCloudTime = 0x368; // FDBDTunableRowHandle
constexpr auto _gasCloudMinimumLifetime = 0x390; // FDBDTunableRowHandle
constexpr auto _gasCloudSimpleCollisionRadius = 0x3b8; // FDBDTunableRowHandle
constexpr auto _gasCloudComplexCollisionRadius = 0x3e0; // FDBDTunableRowHandle
constexpr auto _gasCloudSurvivorDetectionRadius = 0x408; // FDBDTunableRowHandle
constexpr auto _gasCloudDetectionDelay = 0x430; // FDBDTunableRowHandle
constexpr auto _gasCloudCosmeticFadeDuration = 0x458; // FDBDTunableRowHandle
constexpr auto _overlappingTime = 0x480; // float
constexpr auto _dissipating = 0x484; // bool
constexpr auto _overlappingSurvivors = 0x488; // TArray<ACamperPlayer*>
constexpr auto _gasParticleSystem = 0x498; // UParticleSystemComponent*
constexpr auto _simpleCollider = 0x4a0; // USphereComponent*
constexpr auto _complexCollider = 0x4a8; // USphereComponent*
constexpr auto _survivorDetector = 0x4b0; // USpherePlayerOverlapComponent*
constexpr auto _activeGasCloudTracker = 0x4b8; // UActiveGasCloudTrackerComponent*
constexpr auto _cloudSizeModifierTag = 0x4c0; // FGameplayTag
constexpr auto _cumulativeLifetime = 0x4d0; // float
constexpr auto _huskMesh = 0x238; // USkeletalMeshComponent*
constexpr auto _huskCustomizedSkeletalMesh = 0x240; // UCustomizedSkeletalMesh*
constexpr auto _shouldDeactivateVFX = 0x248; // bool
constexpr auto _updateWeaponAccessories = 0x254; // bool
constexpr auto _shouldWeaponBeVisible = 0x255; // bool
constexpr auto PS_CameraEffect = 0x280; // UParticleSystem*
constexpr auto PS_CameraEffectNonExtremeContent = 0x288; // UParticleSystem*
constexpr auto BaseCamera = 0x290; // APlayerCameraManager*
constexpr auto RelativeTransform = 0x2a0; // FTransform
constexpr auto BaseFOV = 0x2d0; // float
constexpr auto bAllowMultipleInstances = 0x2d4; // char : 1
constexpr auto bResetWhenRetriggered = 0x2d4; // char : 1
constexpr auto EmittersToTreatAsSame = 0x2d8; // TArray<AEmitterCameraLensEffectBase*>
constexpr auto DistFromCamera = 0x2e8; // float
